name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install Hugging Face CLI
        run: pip install -U "huggingface_hub[cli]"
        
      - name: Upload to Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli upload SG-27/anime-suggester . . --repo-type space --token $HF_TOKEN
