name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Hugging Face Library
        run: pip install huggingface_hub
        
      - name: Upload using Python
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cat << 'EOF' > upload.py
          import os
          from huggingface_hub import HfApi
          
          api = HfApi()
          api.upload_folder(
              folder_path=".",
              repo_id="SG-27/anime-suggester",
              repo_type="space",
              token=os.environ.get("HF_TOKEN"),
              ignore_patterns=[".git/*", ".github/*"]
          )
          EOF
          python upload.py
